apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-envoy
spec:
  selector:
    matchLabels:
      app: front-envoy
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: front-envoy
        tier: frontend
    spec:
      containers:
        - name: app2
          image: tak2siva/k8s_front_envoy:latest
          ports:
            - name: http
              containerPort: 80
            - name: admin
              containerPort: 8001
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/my-config/
          # command: ["tail"]
          # args: ["-f", "/dev/null"]
          command: ["/usr/local/bin/envoy"]
          args: ["-c", "/etc/my-config/front-envoy.json", "--service-cluster", "front-proxy", "--v2-config-only"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: front-envoy-config