kind: Service
apiVersion: v1
metadata:
  name: front-envoy
spec:
  selector:
    app: front-envoy
    tier: frontend
  ports:
  - protocol: TCP
    name: http
    port: 80
    nodePort: 30080
  - protocol: TCP
    name: admin
    port: 8001
    nodePort: 30081
  type: NodePort