# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Content" do
    optional :value, :string, 1
  end
end

Content = Google::Protobuf::DescriptorPool.generated_pool.lookup("Content").msgclass
