apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
        tier: backend
    spec:
      containers:
        - name: app2
          image: tak2siva/k8s_app2:latest
          ports:
            - name: http
              containerPort: 4568
          volumeMounts:
            - name: config-volume
              mountPath: /etc/my-config/
      volumes:
        - name: config-volume
          configMap:
            name: special-config
