apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: app1
spec:
    selector:
        matchLabels:
            app: app1
            tier: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: app1
                tier: backend
        spec:
            containers:
              - name: app1
                image: k8s_app1:latest
                imagePullPolicy: Never
                ports:
                  - name: http
                    containerPort: 4567
                  - name: grpc
                    containerPort: 50051
              - name: envoy-sidecar
                image: k8s_front_proxy:latest
                imagePullPolicy: Never
                ports:
                  - name: http
                    containerPort: 80
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/my-config/
                command: ["/usr/local/bin/envoy"]
                args: ["-c", "/etc/my-config/sidecar-envoy.json", "--service-cluster", "app1-sidecar", "--v2-config-only"]
            volumes:
              - name: config-volume
                configMap:
                  name: app1-sidecar-config