kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: app1
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    name: http
    nodePort: 30005
  - port: 50052
    name: grpc
    nodePort: 30052
  type: NodePort