apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
      tier: monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
        tier: monitor
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - name: http
              containerPort: 9411